create  TABLE employee(
 EMPID BIGINT AUTO_INCREMENT PRIMARY KEY,
 FIRST_NAME VARCHAR(16) NOT NULL,
 LAST_NAME VARCHAR(16) NOT NULL ,
 EMAIL_ID VARCHAR(50) NOT NULL UNIQUE,
 MANAGER_NAME VARCHAR(50) NOT NULL,
 MOBILE_NUMBER VARCHAR(24)
);
